# Generated by Django 5.0.1 on 2024-12-02 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Oftalmologos', '0001_initial'),
        ('Recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='oftalmologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oftalmologos.oftalmologo'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.paciente'),
        ),
    ]
