# Generated by Django 5.0.1 on 2024-12-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=30)),
                ('apellido_paciente', models.CharField(max_length=30)),
                ('rut_paciente', models.CharField(max_length=9)),
            ],
        ),
    ]
